-- Fuze Ecoteer OS - first Supabase schema
-- Paste this into Supabase SQL Editor and run it once.

create table if not exists public.projects (
  code text primary key,
  name text not null,
  department text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.projects (code, name, department)
values
  ('PTP', 'Perhentian Turtle Project', 'Perhentian'),
  ('PMRS', 'Perhentian Marine Research Station', 'Perhentian'),
  ('PEEP', 'Perhentian Eco Education Project', 'Perhentian')
on conflict (code) do update
set name = excluded.name,
    department = excluded.department;

create table if not exists public.project_leaders (
  project text primary key references public.projects(code),
  leader_name text not null,
  email text,
  reminder_day text not null default 'Friday',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.project_leaders (project, leader_name)
values
  ('PTP', 'Shafiqah'),
  ('PMRS', 'Carmen'),
  ('PEEP', 'Balqis')
on conflict (project) do nothing;

create table if not exists public.impact_entries (
  id bigint generated by default as identity primary key,
  project text not null references public.projects(code),
  activity_type text not null,
  entry_date date not null,
  leader text,
  location text,
  metrics_json jsonb not null default '{}'::jsonb,
  story_highlight text,
  impact_message text,
  photo_video_link text,
  partner_stakeholder text,
  best_for_social boolean not null default false,
  best_for_website boolean not null default false,
  follow_up_needed text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists impact_entries_project_idx
  on public.impact_entries(project);

create index if not exists impact_entries_entry_date_idx
  on public.impact_entries(entry_date desc);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  project text not null references public.projects(code),
  volunteer_name text not null,
  email text,
  country text,
  start_date date,
  end_date date,
  hours numeric not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists volunteers_project_idx
  on public.volunteers(project);

create table if not exists public.organisations (
  id bigint generated by default as identity primary key,
  name text not null,
  organisation_type text,
  country text,
  website text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  organisation_id bigint references public.organisations(id),
  full_name text not null,
  email text,
  phone text,
  role_title text,
  contact_type text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text,
  action text not null,
  actor_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Temporary starter policies.
-- These allow the current public form/dashboard to work before login is added.
-- Once authentication is added, replace these with role-based policies.

alter table public.projects enable row level security;
alter table public.project_leaders enable row level security;
alter table public.impact_entries enable row level security;
alter table public.volunteers enable row level security;
alter table public.organisations enable row level security;
alter table public.contacts enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "Public can read projects" on public.projects;
create policy "Public can read projects"
on public.projects for select
to anon
using (true);

drop policy if exists "Public can read leaders" on public.project_leaders;
create policy "Public can read leaders"
on public.project_leaders for select
to anon
using (true);

drop policy if exists "Public can update leaders during setup" on public.project_leaders;
create policy "Public can update leaders during setup"
on public.project_leaders for update
to anon
using (true)
with check (true);

drop policy if exists "Public can read impact entries during setup" on public.impact_entries;
create policy "Public can read impact entries during setup"
on public.impact_entries for select
to anon
using (true);

drop policy if exists "Public can submit impact entries during setup" on public.impact_entries;
create policy "Public can submit impact entries during setup"
on public.impact_entries for insert
to anon
with check (true);

drop policy if exists "Public can read volunteers during setup" on public.volunteers;
create policy "Public can read volunteers during setup"
on public.volunteers for select
to anon
using (true);

drop policy if exists "Public can submit volunteers during setup" on public.volunteers;
create policy "Public can submit volunteers during setup"
on public.volunteers for insert
to anon
with check (true);
